language: rust
jobs:
  include:
    - stage: test
      os: linux
      script:
        - rustup toolchain install nightly
        - rustup component add --toolchain=nightly clippy-preview
        - cargo +nightly clippy
        - cargo build --verbose
        - cargo test --verbose
    - 
      os: osx
      script:
        - rustup toolchain install nightly
        - rustup component add --toolchain=nightly clippy-preview
        - cargo +nightly clippy
        - cargo build --verbose
        - cargo test --verbose
        
    # deploy crates and documentation conditionally
    # deploy on cargo if tagged master release
    - stage: deploy
      os:
        - linux
      if: tag =~ ^v[0-9]+\.[0-9]+\.[0-9]+
      # our encrypted cratesio token
      env:
        - secure: "JXnAcT0TcXb0lAs4A53wsnUTaJFZu2uRECYGz3fYKcFlI+47Htl6j7BVI25PRouREObWCAf30VGXWYCzp1Jn/KftXNjEfzduw794Dl1g22HiazGm0k7D3ONTDinsgbadJ0QoCRYthjwFvVXuLNKfI1H+/6JddX5RDhIhvE82O1yL3T3oh4keGwIrDh0snwoFXRxFJGyfREHkF7dztZgwxSXctTPcBlfrbSjWIea84eonXr9SU229gKeXS3sKd/mjwzubJ4bzWvM9nhpu4dZtxvAm95Af1akAvxPnXM5vjbXkrJZflAIxs6Qu6sc4bqYvTQiDW5rJUNz8Sa0z2ESOiu0wQVC7Tj7WtUlZ1EEwemb7QUOw05Ocv+LPqZrEXRPtJLa952OUhIOyWRHnEehKmE34gILW1HbgOTO5jqdTQbRpPlXrXL6QdCqqBvYkgMkuiFSgXdZiuerYY6yGHhjuS3kd77XPBnWl4cU/S3pESkH7DNvjraI6DoyBIh62Ua3oYeAwFSmyvB0bB0BUaw2R+sE6ljxL45HOT3NeB/Pxwga9b2oxzlpxAv3kRyWLL155eJt7pNYAM+12wFjvnSDR8lPKsY5c+fow527ZW+4++/N1Qc85+mRFiwfIEYmkGmjqm50TUB0TxdQyyWAe5Yq+YnKYsbdjMNiqgTaomONW6sw=" 
      script:
        - |
          cargo publish --token ${CRATESIO_TOKEN} --manifest-path Cargo.toml
